services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: ./frontend # Путь к папке с Dockerfile
    ports:
      - "80:80"           # Проброс портов
    depends_on:
      - backend           # Зависимости