services:
  backend:
    build: 
      context: ./java-backend  # Путь к папке с Dockerfile бэкенда
    ports:
      - "8080:8080"       # Проброс порта для локальной разработки
  
  frontend:
    build:
      context: ./react-frontend  # Путь к папке с Dockerfile фронтенда
    ports:
      - "80:80"           # Доступ по http://localhost
    depends_on:
      - backend           # Ждём старта бэкенда